name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode SSH Private Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d -i > deploy_key
        shell: bash
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: deploy_key
          
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            # 1. Переходим в рабочую директорию
            cd /root/cse-upload
            
            # 2. Обновляем код из GitHub
            git pull
            
            # 3. Устанавливаем зависимости (если меняли package.json)
            npm install --silent
            
            # 4. Перезапускаем PM2-процесс для cse-upload
            pm2 restart cse-upload
            pm2 save
